$id   = $ARGV[0];
$Time = $ARGV[1];
system("mkdir ./Logs/$Time");
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/$Time/kernel_$id\_$Time\_1.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/$Time/kernel_$id\_$Time\_2.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/$Time/kernel_$id\_$Time\_3.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/$Time/kernel_$id\_$Time\_4.log");
sleep 2;
system("\nadb -s $id wait-for-device");
sleep 10;
system("adb -s $id root");
system("\nadb -s $id wait-for-device");
sleep 5;
system("adb -s $id shell cat /proc/kmsg -v threadtime | tee ./Logs/$Time/kernel_$id\_$Time\_5.log");

